services:
    php-fpm:
        container_name: huge-dataset-api-php
        build:
            context: .
            dockerfile: .docker/php-fpm/Dockerfile
            args:
                USER_ID: ${USER_ID:-0}
        restart: unless-stopped
        user: ${USER_ID:-0}:${GROUP_ID:-0}
        environment:
            XDEBUG_CONFIG: client_host=${XDEBUG_REMOTE_HOST} client_port=${XDEBUG_STORM_PORT}
            PHP_IDE_CONFIG: serverName=${XDEBUG_STORM_SERVER_NAME}
        volumes:
            -   ./:/app
            - ./.docker/php-fpm/entrypoint.sh:/usr/local/bin/entrypoint.sh
            - ./.docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
        entrypoint: [ "/usr/local/bin/entrypoint.sh" ]
        command: [ "php-fpm" ]
        depends_on:
            -   redis
        networks:
            - internal

    nginx:
        container_name: huge-dataset-api-nginx
        build:
            context: .
            dockerfile: ./.docker/nginx/Dockerfile
        volumes:
            - ./:/app:cached
            - ./.docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8000:80"
        restart: unless-stopped
        depends_on:
            -   php-fpm
        networks:
            - internal

    redis:
        container_name: huge-dataset-api-redis
        image: redis:7.0-alpine
        ports:
            - "6379:6379"
        restart: unless-stopped
        volumes:
            - redis_data:/data
        networks:
            - internal

volumes:
    redis_data: { }

networks:
    internal:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${SUBNET_IP}/${SUBNET_MASK}
